[package]
name = "rafka-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jsonc-parser = { version = "0.27", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
